version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.1
    network_mode: host
    container_name: elasticsearch
    restart: always
    environment:
      - network.host=10.150.0.22
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - ./es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.3.1
    container_name: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://10.150.0.22:9200/
    ports:
      - 127.0.0.1:5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.3.1
    network_mode: host
    container_name: logstash
    restart: always
    environment:
      - http.host=10.150.0.22
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline

